# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build
on:
  pull_request:
    branches: ["main"]
    
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup TinyGo
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        id: setup
        with:
          version: "v0.30.0"

      - name: Setup Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "canary"

      - name: Build application
        shell: bash
        run: |
          spin build
