# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release

on:
  push:
    tags:
      - "v*"

permissions: write-all

jobs:
  build:
    name: Build and release explorer
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Setup `spin`
        uses: fermyon/actions/spin/setup@v1

  assets:
    name: Build and release assets
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "canary"

      - name: "Install TinyGo"
        uses: rajatjindal/setup-actions/tinygo@v0.0.1
        with:
          version: 'v0.30.0'

      - name: "Build"
        run: spin build

      - name: generate checksums
        run: |
          sha256sum explorer/spin-kv-explorer.wasm > checksums.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            explorer/spin-kv-explorer.wasm
            checksums.txt
